### PR TITLE
fix bad merge

### PR DESCRIPTION
**Pull request by tomwans**
This resulted in preStop hooks run twice.

CC @ardakuyumcu who found this

### CODE REVIEW

**Comment by tomwans** [comment]
PTAL #compute #mobile-client-networking-failures

**Review by murongl-lyft — APPROVED** [review]

**Comment by abhinavdahiya** [comment]
Since we are changing the CARRY patches, can you maybe expand more on what you mean by bad merge.
- was this incorrectly added because of bad rebase
- Or a previous CARRY patch was incorrect and this is fixing that.

Also is this changing upstream behavior or changing lyft specific custom behavior ?

**Comment by tomwans** [comment]
> was this incorrectly added because of bad rebase

I don't think any of this logic was intentional. The code as it was would run preStop hooks twice for every container, in sequence, due to a bad merge of the patch. This change fixes it so that it runs the preStop hook only once. You can consider this making the lyft-specific behavior match upstream (running the preStop hook only once).

**Comment by abhinavdahiya** [comment]
So if we apply all the Lyft patches on top of new k8s version , we will need this commit too, right?

but if we use upstream k8s release as-is, this is not a divergent behavior from upstream and this commit is not required, right?

**Comment by tomwans** [comment]
I'm not sure if we will need this commit as well - it depends on the underlying code and how it is organized I think. I think the problem with this latest patch is that the code changed under us enough that it resulted in a duplicate line of code. The upstream code is so different at this point I doubt our patches will merge cleanly and we will have to probably manually create a new set of patches in case we did need these.

**Pull request merged**
